instruction = {
    'mean': 'mean(list):\n\tReturn the sample arithmetic mean.',
    'median': 'median(list):\n\tReturn the median.',
    'mode': 'mode(list):\n\tReturn the most common data point.',
    'pstdev': 'pstdev(list):\n\tReturn the population standard deviation.',
    'pvariance': 'pvariance(list):\n\tReturn the population variance.',
    'stdev': 'stdev(list):\n\tReturn the sample standard deviation.',
    'variance': 'variance(list):\n\tReturn the sample variance.',
    'ceil': 'ceil(x):\n\tReturn the smallest integer greater than or equal to x.',
    'floor': 'floor(x):\n\tReturn the largest integer less than or equal to x.',
    'fabs': 'fabs(x):\n\tReturn the absolute value of x.',
    'factorial': 'factorial(x):\n\tReturn the x factorial.',
    'fmod': 'fmod(x, y):\n\tReturn the remainder of x divided by y.',
    'log': 'log(x, y):\n\tReturn the value of logy x.',
    'pow': 'pow(x, y):\n\tReturn x raised to the power of y.',
    'sqrt': 'sqrt(x):\n\tReturn the square root of x.',
    'sin': 'sin(x):\n\tReturn the sine of x radians.',
    'cos': 'cos(x):\n\tReturn the cosine of x radians.',
    'tan': 'tan(x):\n\tReturn the tangent of x radians.',
    'degrees': 'degrees(x):\n\tConvert angle x from radians to degrees.',
    'radians': 'radians(x):\n\tonvert angle x from degrees to radians.',
    'cosh': 'cosh(x):\n\tReturn the hyperbolic cosine of x.',
    'sinh': 'sinh(x):\n\tReturn the hyperbolic sine of x.',
    'tanh': 'tanh(x):\n\tReturn the hyperbolic tangent of x.',
    'random': 'random():\n\tReturn the next random floating point number in the range [0.0, 1.0).',
    'seed': 'seed(x):\n\tInitializethe random number generator by x.\nseed():\n\tInitialize the random number generator with current system time.',
    'uniform': 'uniform(x, y):\n\tReturn a random floating point number in [a, b].',
    'randint': 'randint(x, y):\n\tReturn a random integer N in [a, b].',
    'randrange': 'randrange(x):\n\tReturn a random integer N in [0, x).\nrandrange(x, y, z):\n\tReturn a random interger N in [a, b) where N = a + k * c.',
    'choice': 'choice(list):\n\tReturn a random element from a list.',
    'shuffle': 'shuffle(list):\n\tShuffle a list.',
    'sample': 'sample(list, x):\n\tReturn x length list of randomly chosen elements from a list.'
}
